# Generated by Django 4.0.3 on 2022-03-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('username', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=13)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_email', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
